export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_VOCABULARIES = "GET_VOCABULARIES";
export const VOCABULARY_ERROR = "VOCABULARY_ERROR";

export const GET_GREETINGS = "GET_GREETINGS";
export const GREETINGS_ERROR = "GREETINGS_ERROR";
export const INCREMENT_TRY_GREETINGS = "INCREMENT_TRY_GREETINGS";

export const GET_SCORE_VOCABULARY = "GET_SCORE_VOCABULARY";
export const SET_SCORE_VOCABULARY = "SET_SCORE_VOCABULARY";
export const INCREMENT_TRY_VOCABULARY = "INCREMENT_TRY_VOCABULARY";
